- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create storage account
    azure_rm_storageaccount:
      cert_validation_mode: ignore
      resource_group: ansible-inventory-test-rg
      name: hivan02
      account_type: Standard_LRS
  
  - name: Create virtual network
    azure_rm_virtualnetwork:
      cert_validation_mode: ignore
      resource_group: ansible-inventory-test-rg
      name: hivanet
      address_prefixes: "10.10.0.0/16"
  
  - name: Add subnet
    azure_rm_subnet:
      cert_validation_mode: ignore
      resource_group: ansible-inventory-test-rg
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: hivanet
  
  - name: Create public ip
    azure_rm_publicipaddress:
      cert_validation_mode: ignore
      resource_group: ansible-inventory-test-rg
      allocation_method: Static
      name: publicip001
  
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      cert_validation_mode: ignore
      resource_group: ansible-inventory-test-rg
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      cert_validation_mode: ignore
      resource_group: ansible-inventory-test-rg
      name: testnic001
      virtual_network: hivanet
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001
  
  - name: Create virtual machine
    azure_rm_virtualmachine:
      cert_validation_mode: ignore
      resource_group: ansible-inventory-test-rg
      name: testvm001
      vm_size: Standard_B1ms
      storage_account: hivan02
      storage_container: testvm001
      storage_blob: testvm001.vhd
      admin_username: pepew2
      admin_password: P0tita2018!
      network_interfaces: testnic001
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
      